import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'; // Import the Head component

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Admin Book Panel',
  description: 'Generated by Yohanes Bima',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Add the link tag for the favicon */}
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
